# image will be published to ghcr.io/<user>/<name>
name: ublue-tataru-os
# description will be included in the image's metadata
description: Ublue personal os for my laptop I use TataruOS btw

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      # - micro
      # - starship
      - python3-pip
      # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
      # other spins. You can remove if you aren't using yafti, but many native
      # apps and binaries require it, so it's a good idea to always include it
      # if you ever download or compile any custom software on your machine.
      - libadwaita
      # Codecs
      - gstreamer-plugins-espeak
      - lame
      # Add your own below:
      # Example:
      # - tilix
      - firefox
      - kernel-tools
      - langpacks-fr
      - mesa-libGLU
      - alsa-plugins-pulseaudio
      - gnome-themes-extra
      - gtk-murrine-engine
      - neofetch
      - ibus-typing-booster
      # - wine-devel
      # - wine-common
      # - nvidia-exec
      # - kernel-cachyos-bore
      # - waydroid
      - lm_sensors
      - powertop
      - vkBasalt
      - goverlay
      - mangohud
      #- dkms
      #- kernel-devel
      #- libappindicator
      #- libappindicator-gtk3
      #- https://github.com/MiMillieuh/tongfang-laptop-linux-guide/releases/download/ok/tuxedo-control-center-2.0.8-1.x86_64.rpm
      # - https://getlemonade.org/notrpm/acpi_call-1.2.2-1.x86_64.rpm
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - flatpak-builder
    remove:
      #- mesa-va-drivers

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita
      - Celluloid: io.github.celluloid_player.Celluloid
      - Krita: org.kde.krita
      - Calandar: org.gnome.Calendar
      - Weather: org.gnome.Weather
      - Firmware: org.gnome.Firmware
      - Estension-Manager: com.mattjakeman.ExtensionManager
      - Dconf: ca.desrt.dconf-editor
      - Anydesk: com.anydesk.Anydesk
      - Authy: com.authy.Authy
      - Discord: com.discordapp.Discord
      - Teams: com.github.IsmaelMartinez.teams_for_linux
      - Tidal: com.mastermindzh.tidal-hifi
      - Nextcloud: com.nextcloud.desktopclient.nextcloud
      - ZapZap: com.rtosta.zapzap
      - Bottles: com.usebottles.bottles
      - ProtonGE-Flatpak: com.valvesoftware.Steam.CompatibilityTool.Proton-GE
      - GameScope-Flatpak: com.valvesoftware.Steam.Utility.gamescopel
      - VScode: com.visualstudio.code
      - Joplin: net.cozic.joplin_desktop
      - Lutris: net.lutris.Lutris
      - Audacity: org.audacityteam.Audacity
      - Audacity-codecs: org.audacityteam.Audacity.Codecs
      - Chromium: org.chromium.Chromium
      - Chromium-codecs: org.chromium.Chromium.Codecs
      - Filezilla: org.filezillaproject.Filezilla
      - Gimp: org.gimp.GIMP
      - Gimp-FocusBlur: org.gimp.GIMP.Plugin.FocusBlur
      - Gimp-Fourier: org.gimp.GIMP.Plugin.Fourier
      - Gimp-Gmic: org.gimp.GIMP.Plugin.GMic
      - Gimp-LensFun: org.gimp.GIMP.Plugin.Lensfun
      - Gimp-LiquideRescale: org.gimp.GIMP.Plugin.LiquidRescale
      - Gimp-Resynthetizer: org.gimp.GIMP.Plugin.Resynthesizer
      - Evince: org.gnome.Evince
      - TextEditor: org.gnome.TextEditor
      - Totem: org.gnome.Totem
      - Totem-Codecs: org.gnome.Totem.Codecs
      - Totem-YTDL: org.gnome.Totem.Videosite.YouTubeDl
      - Loupe: org.gnome.Loupe
      - Onlyoffice: org.onlyoffice.desktopeditors
      - PrismLauncher: org.prismlauncher.PrismLauncher
      - qBittorent: org.qbittorrent.qBittorrent
      - Remmina: org.remmina.Remmina

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - acpi_call-module.sh
